### PR TITLE
Minor formatting and clippy fixes

### PR DESCRIPTION
**Pull request by barafael**
Super-simple fixes, let me know what you think.

### CODE REVIEW

**Comment by jedrzejboczar** [comment]
Thanks, it's probably a good idea to start using rustfmt/clippy in this crate, especially clippy. Most of the fixes are ok, however, I don't really like the way rustfmt formats all the `.add("error", command! {` blocks in the examples. Would it be possible to add some rustfmt ignore directives to don't do formatting on these regions? There seems to be a `#[rustfmt::skip]` macro that should allow to do this. But you probably need to put it on the whole `main` function? Or could this be used only for a single statement>

**Comment by barafael** [comment]
rustfmt only applies on items indeed, so not easy in this case. I usually just accept whatever rustfmt emits, but I get what you mean here. Let me know your preference.

**Comment by jedrzejboczar** [comment]
I just checked that putting `#[rustfmt::skip]` just before a statement seems to work, e.g.
```diff
diff --git a/examples/errors.rs b/examples/errors.rs
index bf4b3d1..d7ae0c8 100644
--- a/examples/errors.rs
+++ b/examples/errors.rs
@@ -12,6 +12,7 @@ fn may_throw(description: String) -> Result<(), std::io::Error> {
 fn main() -> anyhow::Result<()> {
     let start = Instant::now();

+    #[rustfmt::skip]
     let mut repl = Repl::builder()
         .add("ok", command! {
             "Run a command that just succeeds",
```
The whole `let mut repl = Repl::builder()...` statement seems untouched. 

While I'm ok with accepting what rustfmt suggests in the rest of the code, I'd prefer to keep the formatting of these `Repl::builder` invocations in examples as-is. Could you please add these lines in examples and redo the formatting and then we'll merge this?

**Comment by barafael** [comment]
Nice! Makes sense, almost everything is an item :) so can be skipped.

**Comment by jedrzejboczar** [comment]
Thanks!

**Pull request merged**
